In [1]:
import numpy as np

In [2]:
r = np.array([0,0.1])
g = np.array([-1,0])

ct = np.dot(r,g)
st = np.sqrt(1-ct**2)
if r[1]<=0:
    st = -st
Rx = np.array([[ct, -st], [st, ct]])

print(Rx)
print()
print(np.dot(Rx, r))


[[ 0. -1.]
 [ 1.  0.]]

[-0.1  0. ]


In [10]:
def inUse(a):#will be creating transformation matrix to rotate a onto b
    # a = np.array([-1,0,0])
    print(a)
    a = a/np.linalg.norm(a)
    b = np.array([1,0,0])
    if np.all(a == -b):
        return np.array([[-1, 0, 0],[0,-1,0],[0,0,1]])

    # print("a ",a)
    # print("b ",b)

    v = np.cross(a, b)
    c = a[0]
    skew = np.array([[0, -v[2], v[1]],[v[2],0,-v[0]],[-v[1], v[0], 0]])
    # print("v ",v)
    # print("c ",c)

    rot = np.eye(3) + skew + np.dot(skew, skew)/(1+c)

    # print(rot)
    print(np.dot(rot, a))
    return rot

rot = inUse(np.array([-0.1,0,0]))

print(np.dot(rot, np.array([-0.1,0,0])))

[-0.1, 0, 0]


array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [202]:
a = np.array([0.5, 0.5, 0])
a = a/np.linalg.norm(a)
xaxis = np.array([1,0,0])
yaxis = np.array([0,1,0])
zaxis = np.array([0,0,1])


ct = -np.dot(a, xaxis)
st = np.linalg.norm(np.cross(a, xaxis))
if a[1] > 0:
    st = -st
R = np.array([[ct, -st, 0],[st, ct, 0], [0,0,1]])


print(R)
np.dot(R, a)

[[-0.70710678  0.70710678  0.        ]
 [-0.70710678 -0.70710678  0.        ]
 [ 0.          0.          1.        ]]


array([ 0., -1.,  0.])

In [315]:
a = np.array([0, 1, 1])
a = a/np.linalg.norm(a)
print(a)
xaxis = np.array([1,0,0])
yaxis = np.array([0,1,0])
zaxis = np.array([0,0,1])

ct = np.linalg.norm(np.array([a[0], a[1]]))
st = a[2]

v = np.cross(zaxis, a)
minct = 1 - ct

rot = np.array([[minct*v[0]**2+ct, minct*v[0]*v[1] - v[2]*st, minct*v[0]*v[2]+v[1]*st],
          [minct*v[1]*v[0] + v[2]*st, minct*v[1]**2 + ct, minct*v[1]*v[2] - v[0]*st],
          [minct*v[2]*v[0] - v[1]*st, minct*v[2] * v[1] - v[0]*st, minct*v[2]**2 + ct ]])

print(np.arccos(ct) * 180/np.pi)
print(np.arcsin(st) * 180/np.pi)

# Rx = np.array([[1,0,0],[0,ct,-st],[0,st,ct]])
# print(Rx)
# print()
print(np.dot(rot, a))
# print(np.dot(Rx, np.array([0, 1/2, -1/2])))
print(np.linalg.norm(np.dot(rot, a)))

[0.         0.70710678 0.70710678]
45.00000000000001
44.99999999999999
[0.         0.85355339 0.85355339]
1.2071067811865472


In [333]:
from scipy.spatial.transform import Rotation as R

a = np.array([1, 1, 1])
a = a/np.linalg.norm(a)
print(a)
zaxis = np.array([0,0,1])

sin = a[2]
cross = -np.cross(a, zaxis)
cross = cross/np.linalg.norm(cross)

rotx = R.from_rotvec(np.arcsin(sin) * cross).as_matrix()

print(np.dot(rotx, a))
print(np.linalg.norm(np.dot(rotx, a)))

[0.57735027 0.57735027 0.57735027]
[7.07106781e-01 7.07106781e-01 5.55111512e-17]
1.0000000000000002


In [356]:
a = np.array([1, 1, 0])
a = a/np.linalg.norm(a)
print(a)
xaxis = np.array([0,0,0])

cos = a[0]
cross = -zaxis

angle = np.arccos(cos)
if a[1] < 0:
    angle = -angle

print(np.arccos(cos) * 180/np.pi)

rotz = R.from_rotvec(angle * cross).as_matrix()

print(rotz)

print(np.dot(rotz, a))
print(np.linalg.norm(np.dot(rotz, a)))

[0.70710678 0.70710678 0.        ]
45.00000000000001
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678 -0.        ]
 [-0.          0.          1.        ]]
[ 1.00000000e+00 -2.22044605e-16  0.00000000e+00]
1.0


In [373]:
def getRotation(a):
    print(a)
    a = a/np.linalg.norm(a)
    zaxis = np.array([0,0,1])

    sin = a[2]
    cross = -np.cross(a, zaxis)
    cross = cross/np.linalg.norm(cross)

    roty = R.from_rotvec(np.arcsin(sin) * cross).as_matrix()

    print(np.dot(roty, a))

    cos = np.dot(roty, a)[0]
    cross = -zaxis

    angle = np.arccos(cos)
    if np.dot(roty, a)[1] < 0:
        angle = -angle

    rotz = R.from_rotvec(angle * cross).as_matrix()

    # print(rotz)


    rotToX = np.dot(rotz, rotx)
    print(np.dot(rotToX, a))
    # print(np.linalg.norm(np.dot(rotToX, a)))
    return rotToX

In [392]:
tpp = []
for i in np.arange(0, 8, 1):
    tpp.append(list(np.binary_repr(i, width=3)))

tpp = np.array(tpp).astype(float)
tpp = (tpp == 0) * -1 + tpp
# print(tpp)
for i in range(8):
    rot = inUse(tpp[i])
    ref = tpp[i]/np.linalg.norm(tpp[i])*-2.5
    print(np.dot(rot, ref))
    

[-1. -1. -1.]
[1.00000000e+00 2.91433544e-16 2.77555756e-16]
[-2.5000000e+00 -8.8817842e-16 -8.8817842e-16]
[-1. -1.  1.]
[ 1.00000000e+00  2.91433544e-16 -2.77555756e-16]
[-2.5000000e+00 -8.8817842e-16  8.8817842e-16]
[-1.  1. -1.]
[ 1.00000000e+00 -2.91433544e-16  2.77555756e-16]
[-2.5000000e+00  8.8817842e-16 -8.8817842e-16]
[-1.  1.  1.]
[ 1.00000000e+00 -2.91433544e-16 -2.77555756e-16]
[-2.5000000e+00  8.8817842e-16  8.8817842e-16]
[ 1. -1. -1.]
[1.00000000e+00 1.11022302e-16 9.71445147e-17]
[-2.50000000e+00 -2.22044605e-16 -1.11022302e-16]
[ 1. -1.  1.]
[ 1.00000000e+00  1.11022302e-16 -9.71445147e-17]
[-2.50000000e+00 -2.22044605e-16  1.11022302e-16]
[ 1.  1. -1.]
[ 1.00000000e+00 -1.11022302e-16  9.71445147e-17]
[-2.50000000e+00  2.22044605e-16 -1.11022302e-16]
[1. 1. 1.]
[ 1.00000000e+00 -1.11022302e-16 -9.71445147e-17]
[-2.50000000e+00  2.22044605e-16  1.11022302e-16]
