In [1]:
import numpy as np

In [62]:
#will be creating transformation matrix to rotate a onto b
startpos = np.array([0,1,0])

a = np.array([0, 1, 0])
a = a/np.linalg.norm(a)
b = np.array([1,0,0])

print(a)
print(b)

[0. 1. 0.]
[1 0 0]


In [63]:
v = np.cross(a, b)
c = np.dot(a,b)
skew = np.array([[0, -v[2], v[1]],[v[2],0,-v[0]],[-v[1], v[0], 0]])

print(c)


0.0


In [68]:
rot = np.eye(3) + skew + np.dot(skew, skew)/(1+c)
rot = np.concatenate((np.concatenate((rot, np.zeros((1,3))), axis=0), np.array([0,0,0,1]).reshape((4,1))), axis = 1)

trans = np.eye(4)
trans[0][3] = -startpos[0]
trans[1][3] = -startpos[1]
trans[2][3] = -startpos[2]
final = np.dot(rot, trans)

print(final)
np.dot(final, np.array([0,1,0,1]))


[[ 0.  1.  0. -1.]
 [-1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


array([0., 0., 0., 1.])